### ISSUE TITLE
## Step 1: Create a Task List

### ISSUE THREAD

**Issue by jefferycline1** [jefferycline1/markdown-portfolio#2]
## Step 1: Create a Task List

A task list creates checkboxes for people with access <sup>[:book:](https://help.github.com/articles/github-glossary/#collaborator)</sup>in a repository to check off. They're very useful for tracking issues and pull requests.

If you include a task list in the body of an issue or pull request, you'll see a progress indicator in your issue list. 

Watch out! The syntax for task lists is very specific. Be sure to include the spaces where required, or else they won't render.

#### Example
```suggestion

```

```suggestion

```
- - Outline my portfolio 
```
```suggestion

```
introduction to

```


```
- [x] Additional markup is supported, including @mentions, #references, [links](url), **emphasis**, and <del>HTML tags</del>.
- [x] List syntax is required.
  - You can nest lists below, too!
- [x] This item is completed.
- [ ] This item is not complete.
```

#### Rendered

- [x] Additional markup is supported, including @mentions, #references, [links](url), **emphasis**, and <del>HTML tags</del>.
- [x] List syntax is required.
  - You can nest lists below, too!
- [x] This item is complete.
- [ ] This item is not complete.

### :keyboard: Activity: Add a comment

1. Add a comment to this issue, using Markdown to create a list of items to complete. Your task can include any tasks you wish, or you can use this example:

       - [ ] Turn on GitHub Pages
       - [ ] Outline my portfolio
       - [ ] Introduce myself to the world

1. Use the **Preview** tab to check your markdown formatting.
1. Click **Comment**.

For a printable version of the steps in this course, check out the [Quick Reference Guide](https://lab.github.com/public/communicating-using-markdown.pdf).

<hr>
<h3 align="center">Watch below your comment for my response.</h3>

> _If you perform an expected action and don't see a response from me after a few seconds, refresh the page for your next steps._


__Originally posted by @github-learning-lab in https://github.com/jefferycline1/markdown-portfolio/issues/1#issuecomment-699600417__

**Comment by jefferycline1** [comment]
``

**Comment by jefferycline1** [comment]
-
- Activate GitHub portfolio
- Introduce myself to the world
- - Learn how to properly use markdown
- -use markdown syntax to communicate on GitHub.

```

**Comment by jefferycline1** [comment]
> `

- A

**Comment by jefferycline1** [comment]
>open GitHub portfolio

> Introduce myself to world

> Start hands on learning using  github





> 

>

**Comment by jefferycline1** [comment]
- - []()  open my GitHub portfolio  
- []()introduce myself to world]()[
```suggestion

```
- use markdown resources to comunicate
- [use my provided repos to share my ideas]()

**Comment by jefferycline1** [comment]
- #``open my portfolio
- ```
Learn how to use markdown
- ```

```
```

**Comment by jefferycline1** [comment]
> I didn't see a task list in that comment. Remember, a task list starts with the syntax `- [ ] ` and then the task list item. The formatting is specific! Try again with a new comment. You can copy this one if you would like to see how they look:
> 
> ```
> - [ ] Turn on GitHub Pages
> - [ ] Outline my portfolio
> - [ ] Introduce myself to the world
> ```
> 
> If you would like assistance troubleshooting, create a post on the [GitHub Community](https://github.community/t5/GitHub-Learning-Lab/bd-p/learn) board. You might also want to search for your issue to see if other people have resolved it in the past.
> 
> ### Watch below your comment f

**Comment by jefferycline1** [comment]
- [ ]  Turn on GitHub pages
- [ ]  Outline my Portfolio 
- [ ]  Introduce myself to the world
